"""initial schema: users, products, inventory_ledger, sales, expenses, cogs_components

Revision ID: 0001
Revises:
Create Date: 2026-08-12

Hand-written (not autogenerated, since this environment has no local
Python/DB to run `alembic revision --autogenerate` against) to exactly
match the SQLAlchemy models in app/models/. Keep this in sync manually if
autogenerate isn't run before the next migration.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Native Postgres enum backing MovementDirection. We let op.create_table's
# own column-dispatch create the type (its default checkfirst=True handles
# "does this type already exist" for us) rather than creating it ourselves
# first — doing both was creating it twice and erroring on the second
# CREATE TYPE. We still create/drop it explicitly on downgrade, since
# drop_table doesn't remove the enum type on its own.
movement_direction_enum = sa.Enum("in", "out", name="movementdirection")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("purchase_price_per_unit", sa.Numeric(14, 2), nullable=False),
    )
    op.create_index("ix_products_name", "products", ["name"])

    op.create_table(
        "inventory_ledger",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("product_id", sa.Integer(), sa.ForeignKey("products.id"), nullable=False),
        sa.Column("quantity", sa.Numeric(14, 3), nullable=False),
        sa.Column("direction", movement_direction_enum, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
    )
    op.create_index("ix_inventory_ledger_product_id", "inventory_ledger", ["product_id"])
    op.create_index("ix_inventory_ledger_timestamp", "inventory_ledger", ["timestamp"])

    op.create_table(
        "sales",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("product_id", sa.Integer(), sa.ForeignKey("products.id"), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(14, 2), nullable=False),
    )
    op.create_index("ix_sales_date", "sales", ["date"])

    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(14, 2), nullable=False),
    )
    op.create_index("ix_expenses_category", "expenses", ["category"])
    op.create_index("ix_expenses_date", "expenses", ["date"])

    op.create_table(
        "cogs_components",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("persediaan_awal", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("pembelian_bahan_baku", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("ongkos_kirim", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("biaya_tenaga_kerja", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("biaya_overhead", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("biaya_kemasan", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.Column("persediaan_akhir", sa.Numeric(14, 2), nullable=False, server_default="0"),
        sa.UniqueConstraint("period", name="uq_cogs_components_period"),
    )
    op.create_index("ix_cogs_components_period", "cogs_components", ["period"])


def downgrade() -> None:
    op.drop_table("cogs_components")
    op.drop_table("expenses")
    op.drop_table("sales")
    op.drop_table("inventory_ledger")
    movement_direction_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_table("products")
    op.drop_table("users")
